# -*- coding: utf-8 -*-
"""Ready-to-use WhatsApp notification rule library (auto-applied, all shipped
INACTIVE). Each entry is seeded by ``_create_default_notification_rules`` only
when its model+field exist and (for selection triggers) the value is a real
selection key — so the same catalog is safe across Odoo versions and module
configurations. Messages live in ``custom_body`` (no template records needed).
Generated from a source-verified audit of the Odoo app suite.
"""

RULES = [
    {
        'name': 'Sales order fully invoiced',
        'app': 'Sales',
        'model': 'sale.order',
        'field': 'invoice_status',
        'ttype': 'selection',
        'value': 'invoiced',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, your order {{record_name}} for {{amount_total}} {{currency}} has been fully invoiced. Please reach out if you need a copy of the invoice.',
    },
    {
        'name': 'Subscription activated / In Progress',
        'app': 'Subscriptions',
        'model': 'sale.order',
        'field': 'subscription_state',
        'ttype': 'selection',
        'value': '3_progress',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, your subscription {{record_name}} is now active. Thank you for subscribing with us!',
    },
    {
        'name': 'Subscription paused',
        'app': 'Subscriptions',
        'model': 'sale.order',
        'field': 'subscription_state',
        'ttype': 'selection',
        'value': '4_paused',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, your subscription {{record_name}} has been paused. Reach out to us anytime to resume it.',
    },
    {
        'name': 'Subscription renewed',
        'app': 'Subscriptions',
        'model': 'sale.order',
        'field': 'subscription_state',
        'ttype': 'selection',
        'value': '5_renewed',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, good news! Your subscription {{record_name}} has been renewed. Thank you for staying with us.',
    },
    {
        'name': 'Subscription ended / churned',
        'app': 'Subscriptions',
        'model': 'sale.order',
        'field': 'subscription_state',
        'ttype': 'selection',
        'value': '6_churn',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': "Hi {{partner_name}}, your subscription {{record_name}} has ended. We'd love to have you back any time.",
    },
    {
        'name': 'Recurring payment failed (contract in exception)',
        'app': 'Subscriptions',
        'model': 'sale.order',
        'field': 'payment_exception',
        'ttype': 'boolean',
        'value': 'True',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': "Hi {{partner_name}}, we couldn't process the automatic payment for your subscription {{record_name}}. Please update your payment method to avoid interruption.",
    },
    {
        'name': 'Rental reserved / ready for pickup',
        'app': 'Rental',
        'model': 'sale.order',
        'field': 'rental_status',
        'ttype': 'selection',
        'value': 'pickup',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, your rental {{record_name}} is reserved and ready for pickup. See you soon!',
    },
    {
        'name': 'Rental items picked up (out with customer)',
        'app': 'Rental',
        'model': 'sale.order',
        'field': 'rental_status',
        'ttype': 'selection',
        'value': 'return',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, your rental {{record_name}} has been picked up. Please return the items by the agreed date. Enjoy!',
    },
    {
        'name': 'Rental returned / completed',
        'app': 'Rental',
        'model': 'sale.order',
        'field': 'rental_status',
        'ttype': 'selection',
        'value': 'returned',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': "Hi {{partner_name}}, we've received the return of your rental {{record_name}}. Thank you for renting with us!",
    },
    {
        'name': 'Invoice fully paid (payment received)',
        'app': 'Invoicing & Accounting',
        'model': 'account.move',
        'field': 'payment_state',
        'ttype': 'selection',
        'value': 'paid',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, we have received your payment for invoice {{record_name}}. The full amount of {{amount_total}} {{currency}} is now settled. Thank you!',
    },
    {
        'name': 'Invoice partially paid',
        'app': 'Invoicing & Accounting',
        'model': 'account.move',
        'field': 'payment_state',
        'ttype': 'selection',
        'value': 'partial',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, we have recorded a partial payment against invoice {{record_name}} (total {{amount_total}} {{currency}}). A balance remains outstanding — please reach out if you need a statement.',
    },
    {
        'name': 'Payment processed (paid)',
        'app': 'Invoicing & Accounting',
        'model': 'account.payment',
        'field': 'state',
        'ttype': 'selection',
        'value': 'paid',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, your payment of {{amount_total}} {{currency}} dated {{date}} has been processed successfully. Thank you for your business.',
    },
    {
        'name': 'Payment rejected',
        'app': 'Invoicing & Accounting',
        'model': 'account.payment',
        'field': 'state',
        'ttype': 'selection',
        'value': 'rejected',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, unfortunately your payment of {{amount_total}} {{currency}} dated {{date}} could not be processed. Please contact us to arrange an alternative.',
    },
    {
        'name': 'Purchase order cancelled',
        'app': 'Purchase',
        'model': 'purchase.order',
        'field': 'state',
        'ttype': 'selection',
        'value': 'cancel',
        'recipient': 'vendor',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, please note that purchase order {{record_name}} has been cancelled. Kindly disregard the previous request. Thank you for your understanding.',
    },
    {
        'name': 'Purchase agreement confirmed',
        'app': 'Purchase',
        'model': 'purchase.requisition',
        'field': 'state',
        'ttype': 'selection',
        'value': 'confirmed',
        'recipient': 'vendor',
        'phone_field': 'vendor_id.mobile',
        'body': 'Hello {{partner_name}}, the purchase agreement {{record_name}} has been confirmed. We look forward to working with you under this agreement. Thank you.',
    },
    {
        'name': 'Order ready for dispatch / pickup',
        'app': 'Inventory & Delivery',
        'model': 'stock.picking',
        'field': 'state',
        'ttype': 'selection',
        'value': 'assigned',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, your order {{record_name}} is now ready. We will dispatch it shortly. Thank you.',
    },
    {
        'name': 'Subcontracted manufacturing order confirmed',
        'app': 'Manufacturing',
        'model': 'mrp.production',
        'field': 'state',
        'ttype': 'selection',
        'value': 'confirmed',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': 'Hello {{partner_name}}, manufacturing order {{record_name}} has been confirmed and assigned to you. Please proceed with production. Thank you.',
    },
    {
        'name': 'Subcontracted manufacturing order completed',
        'app': 'Manufacturing',
        'model': 'mrp.production',
        'field': 'state',
        'ttype': 'selection',
        'value': 'done',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': 'Hello {{partner_name}}, manufacturing order {{record_name}} has been marked as completed. Thank you for your work.',
    },
    {
        'name': 'Quality check failed',
        'app': 'Quality',
        'model': 'quality.check',
        'field': 'quality_state',
        'ttype': 'selection',
        'value': 'fail',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, quality check {{record_name}} did not pass inspection. Our team will contact you regarding the next steps.',
    },
    {
        'name': 'Repair order confirmed',
        'app': 'Repair',
        'model': 'repair.order',
        'field': 'state',
        'ttype': 'selection',
        'value': 'confirmed',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, your repair order {{record_name}} has been confirmed. We will keep you posted as work progresses.',
    },
    {
        'name': 'Repair started (under repair)',
        'app': 'Repair',
        'model': 'repair.order',
        'field': 'state',
        'ttype': 'selection',
        'value': 'under_repair',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, work has started on your repair order {{record_name}}. Our team is now servicing your item.',
    },
    {
        'name': 'Repair order cancelled',
        'app': 'Repair',
        'model': 'repair.order',
        'field': 'state',
        'ttype': 'selection',
        'value': 'cancel',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, your repair order {{record_name}} has been cancelled. Please contact us if you have any questions.',
    },
    {
        'name': 'Lead converted to opportunity',
        'app': 'CRM',
        'model': 'crm.lead',
        'field': 'type',
        'ttype': 'selection',
        'value': 'opportunity',
        'recipient': 'customer',
        'phone_field': 'phone',
        'body': 'Hello {{partner_name}}, thank you for your interest. Our sales team is now working on your request "{{record_name}}" and will be in touch shortly.',
    },
    {
        'name': 'Task approved',
        'app': 'Project & Field Service',
        'model': 'project.task',
        'field': 'state',
        'ttype': 'selection',
        'value': '03_approved',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, your task "{{record_name}}" has been approved and is ready to move forward. Thank you.',
    },
    {
        'name': 'Task completed',
        'app': 'Project & Field Service',
        'model': 'project.task',
        'field': 'state',
        'ttype': 'selection',
        'value': '1_done',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, your task "{{record_name}}" has been completed. Please let us know if you have any questions.',
    },
    {
        'name': 'Task cancelled',
        'app': 'Project & Field Service',
        'model': 'project.task',
        'field': 'state',
        'ttype': 'selection',
        'value': '1_canceled',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, your task "{{record_name}}" has been cancelled. Please contact us if you need any clarification.',
    },
    {
        'name': 'Changes requested on task',
        'app': 'Project & Field Service',
        'model': 'project.task',
        'field': 'state',
        'ttype': 'selection',
        'value': '02_changes_requested',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, changes have been requested on your task "{{record_name}}". We will follow up with the details shortly.',
    },
    {
        'name': 'Field service job marked done',
        'app': 'Project & Field Service',
        'model': 'project.task',
        'field': 'fsm_done',
        'ttype': 'boolean',
        'value': 'True',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, our team has completed the on-site work for "{{record_name}}". Thank you for choosing us.',
    },
    {
        'name': 'Project flagged off track',
        'app': 'Project & Field Service',
        'model': 'project.project',
        'field': 'last_update_status',
        'ttype': 'selection',
        'value': 'off_track',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, we want to let you know that the project "{{record_name}}" is currently off track. We are addressing it and will update you soon.',
    },
    {
        'name': 'Project back on track',
        'app': 'Project & Field Service',
        'model': 'project.project',
        'field': 'last_update_status',
        'ttype': 'selection',
        'value': 'on_track',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, good news: the project "{{record_name}}" is on track. Thank you for your patience.',
    },
    {
        'name': 'Project delivered / closed',
        'app': 'Project & Field Service',
        'model': 'project.project',
        'field': 'last_update_status',
        'ttype': 'selection',
        'value': 'done',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, the project "{{record_name}}" has been completed. It has been a pleasure working with you.',
    },
    {
        'name': 'Milestone reached',
        'app': 'Project & Field Service',
        'model': 'project.milestone',
        'field': 'is_reached',
        'ttype': 'boolean',
        'value': 'True',
        'recipient': 'customer',
        'phone_field': 'project_id.partner_id.mobile',
        'body': 'Hello {{partner_name}}, the milestone "{{record_name}}" has been reached. Thank you for following along.',
    },
    {
        'name': 'Attendance marked',
        'app': 'Events',
        'model': 'event.registration',
        'field': 'state',
        'ttype': 'selection',
        'value': 'done',
        'recipient': 'customer',
        'phone_field': 'phone',
        'body': 'Hi {{partner_name}}, thank you for attending {{record_name}}. We hope you enjoyed the event and look forward to seeing you again.',
    },
    {
        'name': 'Registration cancelled',
        'app': 'Events',
        'model': 'event.registration',
        'field': 'state',
        'ttype': 'selection',
        'value': 'cancel',
        'recipient': 'customer',
        'phone_field': 'phone',
        'body': 'Hi {{partner_name}}, your registration for {{record_name}} has been cancelled. Please contact us if this was not expected.',
    },
    {
        'name': 'POS order paid',
        'app': 'eCommerce & POS',
        'model': 'pos.order',
        'field': 'state',
        'ttype': 'selection',
        'value': 'paid',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, we have received your payment for order {{record_name}} ({{amount_total}} {{currency}}). Thank you for shopping with us!',
    },
    {
        'name': 'POS order invoiced',
        'app': 'eCommerce & POS',
        'model': 'pos.order',
        'field': 'state',
        'ttype': 'selection',
        'value': 'invoiced',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, an invoice has been issued for your order {{record_name}} totalling {{amount_total}} {{currency}}. Please reach out if you have any questions.',
    },
    {
        'name': 'Time off approved',
        'app': 'Time Off',
        'model': 'hr.leave',
        'field': 'state',
        'ttype': 'selection',
        'value': 'validate',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, your time off request "{{record_name}}" has been approved. Enjoy your time off!',
    },
    {
        'name': 'Time off refused',
        'app': 'Time Off',
        'model': 'hr.leave',
        'field': 'state',
        'ttype': 'selection',
        'value': 'refuse',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, unfortunately your time off request "{{record_name}}" has been refused. Please contact your manager for details.',
    },
    {
        'name': 'Leave allocation approved',
        'app': 'Time Off',
        'model': 'hr.leave.allocation',
        'field': 'state',
        'ttype': 'selection',
        'value': 'validate',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, your time off allocation "{{record_name}}" has been approved and added to your balance.',
    },
    {
        'name': 'Expense report approved',
        'app': 'Expenses',
        'model': 'hr.expense.sheet',
        'field': 'state',
        'ttype': 'selection',
        'value': 'approve',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, your expense report "{{record_name}}" for {{amount_total}} {{currency}} has been approved.',
    },
    {
        'name': 'Expense report reimbursed',
        'app': 'Expenses',
        'model': 'hr.expense.sheet',
        'field': 'state',
        'ttype': 'selection',
        'value': 'done',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, your expense report "{{record_name}}" for {{amount_total}} {{currency}} has been reimbursed.',
    },
    {
        'name': 'Expense report refused',
        'app': 'Expenses',
        'model': 'hr.expense.sheet',
        'field': 'state',
        'ttype': 'selection',
        'value': 'cancel',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, your expense report "{{record_name}}" for {{amount_total}} {{currency}} has been refused. Please contact your approver.',
    },
    {
        'name': 'Expense approved',
        'app': 'Expenses',
        'model': 'hr.expense',
        'field': 'state',
        'ttype': 'selection',
        'value': 'approved',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, your expense "{{record_name}}" for {{amount_total}} {{currency}} has been approved.',
    },
    {
        'name': 'Appraisal confirmed/scheduled',
        'app': 'Appraisal',
        'model': 'hr.appraisal',
        'field': 'state',
        'ttype': 'selection',
        'value': 'pending',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, your appraisal has been confirmed and is scheduled for {{date}}. Please prepare your feedback.',
    },
    {
        'name': 'Appraisal completed',
        'app': 'Appraisal',
        'model': 'hr.appraisal',
        'field': 'state',
        'ttype': 'selection',
        'value': 'done',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, your appraisal has been completed. Thank you for your participation.',
    },
    {
        'name': 'Appraisal goal completed',
        'app': 'Appraisal',
        'model': 'hr.appraisal.goal',
        'field': 'progression',
        'ttype': 'selection',
        'value': '100',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Hi {{partner_name}}, congratulations! Your goal "{{record_name}}" has been marked as 100% complete.',
    },
    {
        'name': 'Appointment booked / confirmed',
        'app': 'Appointments',
        'model': 'calendar.event',
        'field': 'appointment_status',
        'ttype': 'selection',
        'value': 'booked',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, your appointment "{{record_name}}" is confirmed for {{date}}. We look forward to seeing you.',
    },
    {
        'name': 'Appointment cancelled',
        'app': 'Appointments',
        'model': 'calendar.event',
        'field': 'appointment_status',
        'ttype': 'selection',
        'value': 'cancelled',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, your appointment "{{record_name}}" scheduled for {{date}} has been cancelled. Please contact us to rebook.',
    },
    {
        'name': 'Appointment marked No Show',
        'app': 'Appointments',
        'model': 'calendar.event',
        'field': 'appointment_status',
        'ttype': 'selection',
        'value': 'no_show',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hello {{partner_name}}, we missed you at your appointment "{{record_name}}" on {{date}}. Reply here to reschedule at a convenient time.',
    },
    {
        'name': 'Membership invoice issued',
        'app': 'Membership',
        'model': 'res.partner',
        'field': 'membership_state',
        'ttype': 'selection',
        'value': 'invoiced',
        'recipient': 'customer',
        'phone_field': 'phone',
        'body': 'Hello {{partner_name}}, your membership invoice has been issued. Please complete payment to activate your membership. Thank you for being with us.',
    },
    {
        'name': 'Membership payment confirmed',
        'app': 'Membership',
        'model': 'res.partner',
        'field': 'membership_state',
        'ttype': 'selection',
        'value': 'paid',
        'recipient': 'customer',
        'phone_field': 'phone',
        'body': 'Hello {{partner_name}}, we have received your membership payment. Your membership is now active. Welcome aboard and thank you!',
    },
    {
        'name': 'Membership cancelled',
        'app': 'Membership',
        'model': 'res.partner',
        'field': 'membership_state',
        'ttype': 'selection',
        'value': 'canceled',
        'recipient': 'customer',
        'phone_field': 'phone',
        'body': 'Hello {{partner_name}}, your membership has been cancelled. If this was not expected or you would like to renew, please contact us.',
    },
    {
        'name': 'Vehicle contract expired',
        'app': 'Fleet',
        'model': 'fleet.vehicle.log.contract',
        'field': 'state',
        'ttype': 'selection',
        'value': 'expired',
        'recipient': 'employee',
        'phone_field': 'purchaser_id.mobile|purchaser_id.phone',
        'body': 'Hello {{partner_name}}, the contract "{{record_name}}" for your vehicle has expired on {{date}}. Please arrange a renewal as soon as possible.',
    },
    {
        'name': 'Vehicle contract now active',
        'app': 'Fleet',
        'model': 'fleet.vehicle.log.contract',
        'field': 'state',
        'ttype': 'selection',
        'value': 'open',
        'recipient': 'employee',
        'phone_field': 'purchaser_id.mobile|purchaser_id.phone',
        'body': 'Hello {{partner_name}}, the contract "{{record_name}}" for your vehicle is now active as of {{date}}. Drive safe!',
    },
    {
        'name': 'Vehicle service completed',
        'app': 'Fleet',
        'model': 'fleet.vehicle.log.services',
        'field': 'state',
        'ttype': 'selection',
        'value': 'done',
        'recipient': 'employee',
        'phone_field': 'purchaser_id.mobile|purchaser_id.phone',
        'body': 'Hello {{partner_name}}, the service "{{record_name}}" on your vehicle has been completed on {{date}}. Your vehicle is ready.',
    },
    {
        'name': 'Survey / certification completed',
        'app': 'Survey',
        'model': 'survey.user_input',
        'field': 'state',
        'ttype': 'selection',
        'value': 'done',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, thank you for completing "{{record_name}}". Your responses have been recorded successfully. We appreciate your participation.',
    },
    {
        'name': 'Order fully delivered',
        'app': 'Sales',
        'model': 'sale.order',
        'field': 'delivery_status',
        'ttype': 'selection',
        'value': 'full',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, great news — your order {{record_name}} has been fully delivered. Thank you for your business!',
    },
    {
        'name': 'Order partially delivered',
        'app': 'Sales',
        'model': 'sale.order',
        'field': 'delivery_status',
        'ttype': 'selection',
        'value': 'partial',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, part of your order {{record_name}} is on its way. The remaining items will follow shortly.',
    },
    {
        'name': 'Vendor bill awaited (ready to be billed)',
        'app': 'Purchase',
        'model': 'purchase.order',
        'field': 'invoice_status',
        'ttype': 'selection',
        'value': 'to invoice',
        'recipient': 'vendor',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Dear {{partner_name}}, the goods/services on PO {{record_name}} have been received. Please submit your invoice for processing.',
    },
    {
        'name': 'Purchase order fully billed',
        'app': 'Purchase',
        'model': 'purchase.order',
        'field': 'invoice_status',
        'ttype': 'selection',
        'value': 'invoiced',
        'recipient': 'vendor',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Dear {{partner_name}}, PO {{record_name}} has been fully billed on our side. Thank you.',
    },
    {
        'name': 'Production started (in progress)',
        'app': 'Manufacturing',
        'model': 'mrp.production',
        'field': 'state',
        'ttype': 'selection',
        'value': 'progress',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': 'Production has started on manufacturing order {{record_name}}.',
    },
    {
        'name': 'MO components ready (materials available)',
        'app': 'Manufacturing',
        'model': 'mrp.production',
        'field': 'reservation_state',
        'ttype': 'selection',
        'value': 'assigned',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': 'All components for manufacturing order {{record_name}} are now available — production can start.',
    },
    {
        'name': 'Wave/batch transfer completed',
        'app': 'Manufacturing',
        'model': 'stock.picking.batch',
        'field': 'state',
        'ttype': 'selection',
        'value': 'done',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': 'Batch transfer {{record_name}} has been fully processed.',
    },
    {
        'name': 'Batch/wave picking started',
        'app': 'Inventory & Delivery',
        'model': 'stock.picking.batch',
        'field': 'state',
        'ttype': 'selection',
        'value': 'in_progress',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': 'Batch {{record_name}} is now in progress — picking has started.',
    },
    {
        'name': 'Repair request received (new)',
        'app': 'Repair',
        'model': 'repair.order',
        'field': 'state',
        'ttype': 'selection',
        'value': 'draft',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': "Hi {{partner_name}}, we've received your repair request {{record_name}}. We'll review it and get back to you shortly.",
    },
    {
        'name': 'Document fully signed',
        'app': 'Sign',
        'model': 'sign.request',
        'field': 'state',
        'ttype': 'selection',
        'value': 'signed',
        'recipient': 'internal',
        'phone_field': 'create_uid.partner_id.phone',
        'body': "Your document '{{record_name}}' has been fully signed by all parties. A signed copy is available.",
    },
    {
        'name': 'Signature request expired',
        'app': 'Sign',
        'model': 'sign.request',
        'field': 'state',
        'ttype': 'selection',
        'value': 'expired',
        'recipient': 'customer',
        'phone_field': 'create_uid.partner_id.phone',
        'body': "The signature request '{{record_name}}' has expired without all signatures. You may need to resend it.",
    },
    {
        'name': 'Quiz/certification passed',
        'app': 'Survey',
        'model': 'survey.user_input',
        'field': 'scoring_success',
        'ttype': 'boolean',
        'value': 'True',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': "Congratulations {{partner_name}}! You passed '{{record_name}}'. Well done!",
    },
    {
        'name': 'Time off request submitted (awaiting approval)',
        'app': 'Time Off',
        'model': 'hr.leave',
        'field': 'state',
        'ttype': 'selection',
        'value': 'confirm',
        'recipient': 'internal',
        'phone_field': 'manager_id.user_id.partner_id.phone',
        'body': 'A time off request from {{record_name}} is awaiting your approval.',
    },
    {
        'name': 'Time off — first-level approval granted',
        'app': 'Time Off',
        'model': 'hr.leave',
        'field': 'state',
        'ttype': 'selection',
        'value': 'validate1',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Your time off request has its first approval and is now pending final approval.',
    },
    {
        'name': 'Expense report submitted (awaiting approval)',
        'app': 'Expenses',
        'model': 'hr.expense.sheet',
        'field': 'state',
        'ttype': 'selection',
        'value': 'submit',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': "An expense report '{{record_name}}' has been submitted and is awaiting your approval.",
    },
    {
        'name': 'Expense report posted to accounting',
        'app': 'Expenses',
        'model': 'hr.expense.sheet',
        'field': 'state',
        'ttype': 'selection',
        'value': 'post',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': "Your expense report '{{record_name}}' has been posted and is queued for reimbursement.",
    },
    {
        'name': 'Expense reimbursement paid',
        'app': 'Expenses',
        'model': 'hr.expense.sheet',
        'field': 'payment_state',
        'ttype': 'selection',
        'value': 'paid',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': "Your expense reimbursement for '{{record_name}}' has been paid. Please check your account.",
    },
    {
        'name': 'Employment contract now running',
        'app': 'HR',
        'model': 'hr.contract',
        'field': 'state',
        'ttype': 'selection',
        'value': 'open',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Your employment contract is now active. Welcome aboard, {{record_name}}!',
    },
    {
        'name': 'Employment contract expired/ended',
        'app': 'HR',
        'model': 'hr.contract',
        'field': 'state',
        'ttype': 'selection',
        'value': 'close',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Your employment contract has reached its end date. HR will be in touch regarding next steps.',
    },
    {
        'name': 'Subscription renewal quotation sent',
        'app': 'Subscriptions',
        'model': 'sale.order',
        'field': 'subscription_state',
        'ttype': 'selection',
        'value': '2_renewal',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, a renewal quotation for your subscription {{record_name}} is ready. Please review to continue your service.',
    },
    {
        'name': 'Subscription health flagged Bad (churn risk)',
        'app': 'Subscriptions',
        'model': 'sale.order',
        'field': 'health',
        'ttype': 'selection',
        'value': 'bad',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': "Subscription {{record_name}} health is now 'Bad' — possible churn risk. Please follow up.",
    },
    {
        'name': 'Sales order locked (finalized)',
        'app': 'Sales',
        'model': 'sale.order',
        'field': 'locked',
        'ttype': 'boolean',
        'value': 'True',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': 'Sales order {{record_name}} has been locked and can no longer be modified.',
    },
    {
        'name': 'Vehicle contract closed/terminated',
        'app': 'Fleet',
        'model': 'fleet.vehicle.log.contract',
        'field': 'state',
        'ttype': 'selection',
        'value': 'closed',
        'recipient': 'internal',
        'phone_field': 'purchaser_id.mobile|purchaser_id.phone',
        'body': 'The contract for vehicle {{record_name}} has been closed/terminated.',
    },
    {
        'name': 'Vehicle service in progress',
        'app': 'Fleet',
        'model': 'fleet.vehicle.log.services',
        'field': 'state',
        'ttype': 'selection',
        'value': 'running',
        'recipient': 'internal',
        'phone_field': 'purchaser_id.mobile|purchaser_id.phone',
        'body': 'A service on vehicle {{record_name}} is now in progress.',
    },
    {
        'name': 'Document sent for signature (action needed)',
        'app': 'Sign',
        'model': 'sign.request',
        'field': 'state',
        'ttype': 'selection',
        'value': 'sent',
        'recipient': 'internal',
        'phone_field': 'create_uid.partner_id.phone',
        'body': "A document '{{record_name}}' is waiting for your signature. Please review and sign.",
    },
    {
        'name': 'Project flagged At Risk',
        'app': 'Project & Field Service',
        'model': 'project.project',
        'field': 'last_update_status',
        'ttype': 'selection',
        'value': 'at_risk',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': "Project '{{record_name}}' status has been set to At Risk.",
    },
    {
        'name': 'Project put on hold',
        'app': 'Project & Field Service',
        'model': 'project.project',
        'field': 'last_update_status',
        'ttype': 'selection',
        'value': 'on_hold',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': "Project '{{record_name}}' has been put On Hold.",
    },
    {
        'name': 'Invoice payment in process (registered, not reconciled)',
        'app': 'Invoicing & Accounting',
        'model': 'account.move',
        'field': 'payment_state',
        'ttype': 'selection',
        'value': 'in_payment',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': "Hi {{partner_name}}, we've registered a payment for invoice {{record_name}} — it is being processed.",
    },
    {
        'name': 'Invoice reversed (credit note applied)',
        'app': 'Invoicing & Accounting',
        'model': 'account.move',
        'field': 'payment_state',
        'ttype': 'selection',
        'value': 'reversed',
        'recipient': 'customer',
        'phone_field': 'partner_id.mobile|partner_id.phone',
        'body': 'Hi {{partner_name}}, invoice {{record_name}} has been reversed via a credit note. No payment is due.',
    },
    {
        'name': 'Manufacturing order ready to close',
        'app': 'Manufacturing',
        'model': 'mrp.production',
        'field': 'state',
        'ttype': 'selection',
        'value': 'to_close',
        'recipient': 'internal',
        'phone_field': 'user_id.partner_id.phone',
        'body': 'Manufacturing order {{record_name}} is finished and ready to be closed/validated.',
    },
    {
        'name': 'Leave allocation refused',
        'app': 'Time Off',
        'model': 'hr.leave.allocation',
        'field': 'state',
        'ttype': 'selection',
        'value': 'refuse',
        'recipient': 'employee',
        'phone_field': 'employee_id.mobile_phone|employee_id.work_phone',
        'body': 'Your time off allocation request has been refused. Please contact HR for details.',
    },
    {
        'name': 'Recruitment — Candidate Hired (check your Hired stage)',
        'app': 'Recruitment',
        'model': 'hr.applicant',
        'field': 'stage_id',
        'ttype': 'many2one',
        'value': 'Contract Signed',
        'recipient': 'customer',
        'phone_field': 'partner_phone|partner_id.mobile|partner_id.phone',
        'body': "Hi {{partner_name}}, welcome aboard! We're delighted to confirm your hiring for {{record_name}}. HR will be in touch with your onboarding details.",
    },
]
