{
    "name": "Sudi Diamond Job Work",
    "version": "19.0.1.0.0",
    "summary": "Diamond job-work receipts, deliveries, and GST invoicing",
    "category": "Inventory/Inventory",
    "author": "Sudi",
    "license": "LGPL-3",
    "depends": [
        "stock",
        "account",
        "l10n_in",
        "mail",
        "product",
        "uom",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/diamond_product_data.xml",
        "data/diamond_job_type_data.xml",
        "views/job_type_views.xml",
        "views/res_partner_views.xml",
        "views/stock_picking_views.xml",
        "views/account_move_views.xml",
        "report/diamond_receipt_report.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": True,
}
