{
    "name": "Sudi Diamond Job Work",
    "version": "19.0.1.2.1",
    "summary": "Diamond job-work receipts, deliveries, and GST invoicing",
    "category": "Inventory/Inventory",
    "author": "Sudi",
    "license": "LGPL-3",
    "depends": [
        "stock",
        "account",
        "hr_timesheet",
        "l10n_in",
        "mail",
        "product",
        "timesheet_grid",
        "uom",
        "website",
        "open_whatsapp_connector",
        "web_auth_otp_login",
    ],
    "data": [
        "security/diamond_security.xml",
        "security/ir.model.access.csv",
        "data/diamond_product_data.xml",
        "data/diamond_job_type_data.xml",
        "data/diamond_timesheet_project_data.xml",
        "data/diamond_notification_data.xml",
        "views/job_type_views.xml",
        "views/res_users_views.xml",
        "views/res_partner_views.xml",
        "views/department_transfer_wizard_views.xml",
        "views/stock_picking_views.xml",
        "views/account_analytic_line_views.xml",
        "views/account_move_views.xml",
        "views/jangad_upload_templates.xml",
        "views/gst_onboarding_templates.xml",
        "report/diamond_receipt_report.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "diamond/static/src/js/jangad_image_viewer.js",
            "diamond/static/src/xml/jangad_image_viewer.xml",
            "diamond/static/src/scss/jangad_image_viewer.scss",
        ],
        "web.assets_frontend": [
            "diamond/static/src/js/jangad_upload.js",
            "diamond/static/src/js/jangad_pwa.js",
            "diamond/static/src/scss/jangad_pwa.scss",
        ],
    },
    "installable": True,
    "application": True,
}
